#!/usr/bin/env -S uv run --script
#
# /// script
# requires-python = ">=3.12"
# dependencies = ["dspy", "gepa[full]", "openai"]
# ///

'''
Teach the student LM (LiquidAI/LFM2.5-2.6B) to handle pi skill invocations like the teacher LM (Qwen/Qwen3.8-27B, use it without thinking/reasoning, so it works fast) using dspy with gepa optimizer.

Steps:
1. Add synthetic user/assistant pair (content + reasoning_content) inserted into the student conversation just AFTER the existing synthetic skills/tools Q&A pairs how skill system works: invoke skill `<skill> SKILL BODY </skill> [USER MESSAGE]` block with user message. Currently, I have placeholder user message, so you can find this part where user asks "How does skill system work? When a skill block is in my latest message, what do I do?".
2. Add synthetic user/assistant pair (content + reasoning_content), one-shot usage of `example` skill (dummy fake skill just as reference), and answer to it: Invoked with no extra text
3. Add synthetic user/assistant pair (content + reasoning_content), one-shot usage of `example` skill (dummy fake skill just as reference), and answer to it: Invoked with "Hello"
4. Add synthetic user/assistant pair (content + reasoning_content), one-shot usage of `example` skill (dummy fake skill just as reference), and answer to it: Invoked with any other text, or asked to "call script"
5. The real skill-invocation user message happens here (it can be one message, but also more than one when testing modes transitions). We will use `tzip` skill here, it could be any skill really used in the future. Test invoking skill `tzip` using modes:
  - default / empty
  - on
  - lite
  - full
  - ultra
  - add more messages to conversation to cover transitions between all previous `tzip` modes. minimum one transitions (all combinations of mode-to-mode transition), but test up to two transitions (random three modes transitions).

Goal 1:
If file `skill-example-LiquidAI-LFM2.5-2.6B.json` is empty file, create it following these rules. If file is not empty, consider this goal fulfilled.
Since reasoning in `skill-example-Qwen-Qwen3.8-27B.json` is based on `Qwen/Qwen3.8-27B` model, in messages where `example` skill is used, convert reasoning to `LiquidAI/LFM2.5-2.6B` style based on `REASONING-LiquidAI-LFM2.5-2.6B.md` in new file `skill-example-LiquidAI-LFM2.5-2.6B.json`.
Set model and sampling params to one from LiquidAI/LFM2.5-2.6B (you can find them in `~/.pi/agent/models.json`).

Goal 2:
You can find minimal conversations in `skill-example-LiquidAI-LFM2.5-2.6B.json` based on `Qwen/Qwen3.8-27B` but written in style of `LiquidAI/LFM2.5-2.6B`.
We need to optimize for any skill usage, so work on synthetic user/assistant pair in step 1. You are allowed to optimize only user and assistant from step 1. Other messages should stay the same, but at the end of conversation, you can invoke other skills to test if it is working explaine in step 5.
Do not touch system message and next two synthetic pairs of messages how to use skills and tools because that is already optimized for this model.

---
Implementation notes (this file):

- Models + API credentials are read at runtime from ~/.pi/agent/models.json
  (provider `llamacpp`). They are never written to any file, log, or state.
- Goal 1 builds `skill-example-LiquidAI-LFM2.5-2.6B.json` (steps 1-4) from the
  Qwen file: same messages, but step-1 teaching pair written explicitly for the
  `<skill> SKILL BODY </skill> [USER MESSAGE]` shape and all `reasoning_content`
  in the example one-shots rewritten in LFM2.5-2.6B voice per
  REASONING-LiquidAI-LFM2.5-2.6B.md. Header uses LFM model + its sampling params.
- Step 5 builds `skill-tzip-LiquidAI-LFM2.5-2.6B.json` = the skill-example
  conversation + 15 interleaved real invocations that switch skills in between:
  the `tzip` skill with nine mode transitions jumping randomly up and down the
  lite/full/ultra ladder (default, full, ultra, on, lite, full, ultra, lite,
  ultra, off) and the `example` skill invoked five times (Hello, call script
  with no parameters, no extra text, a fresh argument, Hello again after
  `tzip off`). Assistant `content` for every message is generated by the
  teacher model (thinking off) on the growing conversation; `reasoning_content`
  is written in LFM voice.
- Goal 2 runs GEPA (`gepa.optimize_anything`): the only optimized text is the
  step-1 pair (user + assistant content + assistant reasoning). The student is
  rolled out (with real read/bash tools) on the frozen prefix
  (system + skills/tools Q&A + optimized step-1 pair + the three frozen example
  one-shots) followed by each of the 15 interleaved test invocations. The
  metric compares the student reply to the teacher reply (exact=1.0,
  containment=0.5). The reflection LM is the teacher (thinking off).
- The optimized step-1 pair is written back into
  `skill-tzip-LiquidAI-LFM2.5-2.6B.json` (and saved to
  `step1-pair-optimized.json`).

You can find models configurations in `~/.pi/agent/models.json`.
Never keep API_BASE and API_KEY in any other file, source code nor logs.
Never leak API_BASE and API_KEY.
Always read them from `models.json`.
'''

import copy
import json
import re
import subprocess
from pathlib import Path

import dspy
import gepa
from gepa import NoImprovementStopper, ScoreThresholdStopper, TimeoutStopCondition
from gepa.optimize_anything import EngineConfig, GEPAConfig, ReflectionConfig, optimize_anything

HERE = Path(__file__).resolve().parent
PI_ROOT = HERE.parents[1]  # /home/mtasic/projects-b/pi-slm

MODELS_JSON = Path.home() / ".pi" / "agent" / "models.json"
QWEN_FILE = HERE / "skill-example-Qwen-Qwen3.8-27B.json"
EXAMPLE_FILE = HERE / "skill-example-LiquidAI-LFM2.5-2.6B.json"
TZIP_FILE = HERE / "skill-tzip-LiquidAI-LFM2.5-2.6B.json"
PAIR_FILE = HERE / "step1-pair-optimized.json"
RUN_DIR = HERE / "gepa_runs" / "skills-usage-3-v2"

STUDENT_MODEL = "LiquidAI/LFM2.5-2.6B"  # thinking: on
TEACHER_MODEL = "Qwen/Qwen3.8-27B"  # thinking: off
PROVIDER = "llamacpp"
SESSION_HEADER = {"x-session-affinity": "dspy-optim"}

TZIP_SKILL_DIR = PI_ROOT / ".agents" / "skills-byterefinery" / "tzip"
TZIP_LOCATION = str(TZIP_SKILL_DIR / "SKILL.md")

MAX_METRIC_CALLS = 200
STUDENT_MAX_TOKENS = 16384

API_BASE = None
API_KEY = None


def say(*parts):
    """Print with API_BASE/API_KEY masked (never leak them)."""
    s = " ".join(str(p) for p in parts)
    for secret in (API_BASE, API_KEY):
        if secret:
            s = s.replace(secret, "***")
    print(s, flush=True)


# ---------------------------------------------------------------------------
# models.json
# ---------------------------------------------------------------------------

def load_model_configs():
    raw = MODELS_JSON.read_text()
    raw = re.sub(r",\s*([}\]])", r"\1", raw)  # models.json allows trailing commas
    cfg = json.loads(raw)
    prov = cfg["providers"][PROVIDER]
    models = {m["id"]: m for m in prov["models"]}
    return prov["baseUrl"], prov["apiKey"], models[STUDENT_MODEL], models[TEACHER_MODEL]


def sampling_body(model_cfg, thinking_kwargs):
    """extra_body for dspy.LM from models.json samplingParams + thinking switch."""
    sp = model_cfg.get("samplingParams", {})
    body = {
        k: sp[k]
        for k in ("top_k", "min_p", "presence_penalty", "frequency_penalty", "repeat_penalty")
        if k in sp
    }
    if thinking_kwargs:
        body["chat_template_kwargs"] = thinking_kwargs
    return body, sp.get("temperature")


def build_lms(api_base, api_key, student_cfg, teacher_cfg):
    s_body, s_temp = sampling_body(student_cfg, {"enable_thinking": True, "preserve_thinking": True})
    student = dspy.LM(
        f"openai/{STUDENT_MODEL}",
        api_base=api_base,
        api_key=api_key,
        model_type="chat",
        temperature=s_temp,
        max_tokens=STUDENT_MAX_TOKENS,
        extra_headers=dict(SESSION_HEADER),
        extra_body=s_body,
    )
    t_body, t_temp = sampling_body(teacher_cfg, {"enable_thinking": False})  # thinking off, so it works fast
    teacher = dspy.LM(
        f"openai/{TEACHER_MODEL}",
        api_base=api_base,
        api_key=api_key,
        model_type="chat",
        temperature=t_temp,
        max_tokens=STUDENT_MAX_TOKENS,
        extra_headers=dict(SESSION_HEADER),
        extra_body=t_body,
    )
    return student, teacher


# ---------------------------------------------------------------------------
# chat / tools / rollouts
# ---------------------------------------------------------------------------

def chat(lm, messages, tools=None):
    """One assistant turn. Returns the assistant message in the recorded file shape."""
    kwargs = {"tools": tools} if tools else {}
    resp = lm.forward(messages=messages, **kwargs)
    m = resp.choices[0].message
    out = {"role": "assistant", "content": m.content}
    if getattr(m, "reasoning_content", None):
        out["reasoning_content"] = m.reasoning_content
    if m.tool_calls:
        out["tool_calls"] = [
            {
                "id": tc.id,
                "type": "function",
                "function": {"name": tc.function.name, "arguments": tc.function.arguments},
            }
            for tc in m.tool_calls
        ]
    return out


def last_skill_dir(messages):
    dirs = re.findall(r'<skill name="[^"]*" location="([^"]+)"', json.dumps(messages))
    return str(Path(dirs[-1]).parent) if dirs else None


def exec_read(path, cwd, skill_dir):
    p = Path(path)
    if not p.is_absolute():
        cands = [Path(d) / p for d in (skill_dir, cwd) if d]
        p = next((c for c in cands if c.is_file()), Path(cwd) / p)
    try:
        return p.read_text()
    except Exception as e:  # noqa: BLE001
        return f"Error reading {path}: {e}"


def exec_bash(command, cwd, skill_dir):
    run_cwd = Path(cwd)
    if skill_dir and re.search(r"(?<!/)\b(scripts|references)/", command):
        run_cwd = Path(skill_dir)  # skill rule: relative paths resolve against the skill dir
    try:
        r = subprocess.run(command, shell=True, cwd=str(run_cwd), capture_output=True, text=True, timeout=30)
        out = (r.stdout + (r.stderr if r.stderr else "")).strip()
        return out or "(no output)"
    except Exception as e:  # noqa: BLE001
        return f"Error running command: {e}"


def rollout(lm, messages, tools, max_turns=4):
    """Multi-turn rollout: execute tool calls until the model replies with content."""
    msgs = list(messages)
    skill_dir = last_skill_dir(msgs)
    transcript = []
    for _ in range(max_turns):
        m = chat(lm, msgs, tools)
        msgs.append(m)
        transcript.append(m)
        if not m.get("tool_calls"):
            return transcript, m
        for tc in m["tool_calls"]:
            name = tc["function"]["name"]
            try:
                args = json.loads(tc["function"]["arguments"] or "{}")
            except json.JSONDecodeError:
                args = {}
            if name == "read":
                result = exec_read(args.get("path", ""), PI_ROOT, skill_dir)
            elif name == "bash":
                result = exec_bash(args.get("command", ""), PI_ROOT, skill_dir)
            else:
                result = f"Error: unknown tool {name}"
            tool_msg = {"role": "tool", "content": str(result), "tool_call_id": tc["id"]}
            msgs.append(tool_msg)
            transcript.append(tool_msg)
    return transcript, transcript[-1]


def user_text_of(msg):
    c = msg.get("content")
    if isinstance(c, list):
        return "".join(p.get("text", "") for p in c if p.get("type") == "text")
    return c or ""


def make_user(text):
    return {"role": "user", "content": [{"type": "text", "text": text}]}


# ---------------------------------------------------------------------------
# LFM-voice reasoning (per REASONING-LiquidAI-LFM2.5-2.6B.md) + step-1 seed
# ---------------------------------------------------------------------------

STEP1_PLACEHOLDER_Q = "How does skill system work? When a skill block is in my latest message, what do I do?"

STEP1_SEED_CONTENT = (
    "A skill invocation is a `<skill> SKILL BODY </skill>` block with the user message after it: "
    "the block carries the skill's instructions, and the text after the closing tag is the argument for this invocation. "
    "I will treat the skill block in my latest message as the active instruction and ignore earlier questions. "
    "I will use the argument after the block as the current argument, not an example from inside the skill. "
    "If there is no argument, I will use the skill's required default wording. "
    "I will follow the skill's Usage rules for the current argument and reply text only with the exact required confirmation: "
    "skill name, current argument or default wording, and required wording."
)

STEP1_SEED_REASONING = (
    "The user wants the rule for a skill block in my latest message. "
    "I will explain the `<skill> SKILL BODY </skill> [USER MESSAGE]` shape: the block is the active instruction, "
    "the text after the block is the current argument, and the reply is the exact confirmation the skill requires."
)

REASON_EXAMPLE_NO_TEXT = (
    "The user is invoking the example skill with no extra text. "
    "The Usage rule says to reply exactly `This is an example skill.` with nothing else. I will reply with that exact line."
)
REASON_EXAMPLE_HELLO_TOOL = (
    'The user invoked the example skill with "Hello". '
    "The Usage rule says not to guess the response: load references/03-hello.md and follow it exactly. Let me read that file."
)
REASON_EXAMPLE_WORLD = (
    "The reference file says to reply exactly `world` with no greeting, punctuation, or commentary. I will reply with that single word."
)
REASON_EXAMPLE_SCRIPT_TOOL = (
    'The user invoked the example skill with "Hi". That is any other text, '
    "so I will pass it as CLI parameters to scripts/example.sh and report the output. Let me run the script."
)
REASON_EXAMPLE_REPORT = (
    "The script printed one line. The skill says to report the output. I will report it in a code block."
)

REASON_EX_HELLO_TOOL = (
    'The user invoked the example skill with "Hello". '
    "The Usage rule says not to guess the response: load references/03-hello.md and follow it exactly. Let me read that file."
)
REASON_EX_HELLO_TOOL_POST_OFF = (
    'The user invoked the example skill with "Hello" after tzip was deactivated. '
    "The Usage rule says to load references/03-hello.md and follow it exactly. Let me read that file."
)
REASON_EX_HELLO_WORLD = (
    "The reference file says to reply exactly `world` with no greeting, punctuation, or commentary. I will reply with that single word."
)
REASON_EX_NOTEXT = (
    "The user is invoking the example skill with no extra text. "
    "The Usage rule says to reply exactly `This is an example skill.` with nothing else. I will reply with that exact line."
)
REASON_EX_CALLSCRIPT_TOOL = (
    "The user asked to call the script without extra text. "
    "The Usage rule says to run scripts/example.sh and report the output. Let me run it without parameters."
)
REASON_EX_TEST_TOOL = (
    'The user invoked the example skill with "Test123". That is any other text, '
    "so I will pass it as CLI parameters to scripts/example.sh and report the output. Let me run the script."
)
REASON_EX_REPORT = (
    "The script printed one line. The skill says to report the output. I will report it in a code block."
)

# Interleaved test sequence: (kind, argument, tool-call reasoning, final reasoning).
# tzip mode transitions jump randomly up and down the lite/full/ultra ladder and end in off;
# the example skill is invoked in between, including a fresh argument and one call after `tzip off`.
SEQ = [
    ("tzip", "", None, "The user is activating tzip with no argument. The default mode is lite. I will reply with the exact confirmation the skill requires."),
    ("tzip", "full", None, "The user is switching tzip from lite to full. I will reply with the exact confirmation the skill requires."),
    ("example", "Hello", REASON_EX_HELLO_TOOL, REASON_EX_HELLO_WORLD),
    ("tzip", "ultra", None, "The user is switching tzip from full to ultra. I will reply with the exact confirmation the skill requires."),
    ("example", "call script", REASON_EX_CALLSCRIPT_TOOL, REASON_EX_REPORT),
    ("tzip", "on", None, "The user is dropping tzip from ultra to on. That is lite mode. I will reply with the exact confirmation the skill requires."),
    ("tzip", "lite", None, "The user is re-confirming tzip lite. I will reply with the exact confirmation the skill requires."),
    ("example", "", None, REASON_EX_NOTEXT),
    ("tzip", "full", None, "The user is switching tzip from lite to full. I will reply with the exact confirmation the skill requires."),
    ("example", "Test123", REASON_EX_TEST_TOOL, REASON_EX_REPORT),
    ("tzip", "ultra", None, "The user is switching tzip from full to ultra. I will reply with the exact confirmation the skill requires."),
    ("tzip", "lite", None, "The user is dropping tzip from ultra to lite. I will reply with the exact confirmation the skill requires."),
    ("tzip", "ultra", None, "The user is jumping tzip from lite to ultra. I will reply with the exact confirmation the skill requires."),
    ("tzip", "off", None, "The user is deactivating tzip. I will reply with the deactivation confirmation it requires."),
    ("example", "Hello", REASON_EX_HELLO_TOOL_POST_OFF, REASON_EX_HELLO_WORLD),
]

# reflection minibatches: default, a mode jump, a drop, each example behavior, the deactivation
TRAIN_ITEM_IDX = [0, 1, 2, 4, 5, 9, 13]


# ---------------------------------------------------------------------------
# Goal 1 — skill-example-LiquidAI-LFM2.5-2.6B.json
# ---------------------------------------------------------------------------

def build_base_conversation():
    """Qwen conversation with LFM-voice reasoning for the example one-shots + step-1 seed."""
    qwen = json.loads(QWEN_FILE.read_text())
    msgs = copy.deepcopy(qwen["messages"])
    tools = copy.deepcopy(qwen["tools"])

    i = next(idx for idx, m in enumerate(msgs) if user_text_of(m).startswith("How does skill system work?"))
    assert msgs[i]["role"] == "user" and msgs[i + 1]["role"] == "assistant"
    msgs[i]["content"] = [{"type": "text", "text": STEP1_PLACEHOLDER_Q}]
    msgs[i + 1]["content"] = STEP1_SEED_CONTENT
    msgs[i + 1]["reasoning_content"] = STEP1_SEED_REASONING

    for m in msgs[i + 2:]:
        if m.get("role") != "assistant":
            continue
        c = m.get("content")
        names = [tc["function"]["name"] for tc in m.get("tool_calls") or []]
        if c == "This is an example skill.":
            m["reasoning_content"] = REASON_EXAMPLE_NO_TEXT
        elif c == "world":
            m["reasoning_content"] = REASON_EXAMPLE_WORLD
        elif c is None and names == ["read"]:
            m["reasoning_content"] = REASON_EXAMPLE_HELLO_TOOL
        elif c is None and names == ["bash"]:
            m["reasoning_content"] = REASON_EXAMPLE_SCRIPT_TOOL
        elif isinstance(c, str) and c.startswith("example.sh output:"):
            m["reasoning_content"] = REASON_EXAMPLE_REPORT
    return msgs, tools


def make_doc(messages, model_id, model_cfg, tools):
    sp = model_cfg.get("samplingParams", {})
    doc = {
        "model": model_id,
        "messages": messages,
        "stream": True,
        "stream_options": {"include_usage": True},
        "max_tokens": model_cfg.get("maxTokens", STUDENT_MAX_TOKENS),
        "tools": tools,
        "chat_template_kwargs": {"enable_thinking": True, "preserve_thinking": True},
    }
    for k in ("temperature", "top_p", "top_k", "min_p", "presence_penalty", "repeat_penalty"):
        if k in sp:
            doc[k] = sp[k]
    return doc


def load_goal1(student_cfg):
    """Return (base_msgs, tools, seed_step1_user, seed_step1_content, seed_step1_reasoning)."""
    if EXAMPLE_FILE.exists() and EXAMPLE_FILE.stat().st_size > 0:
        say(f"Goal 1: {EXAMPLE_FILE.name} is not empty — considered fulfilled, loading it.")
        doc = json.loads(EXAMPLE_FILE.read_text())
        msgs, tools = doc["messages"], doc["tools"]
    else:
        say("Goal 1: creating skill-example-LiquidAI-LFM2.5-2.6B.json from the Qwen file (LFM voice).")
        msgs, tools = build_base_conversation()
        EXAMPLE_FILE.write_text(json.dumps(make_doc(msgs, STUDENT_MODEL, student_cfg, tools), ensure_ascii=False, indent=2) + "\n")
        say(f"  wrote {EXAMPLE_FILE.name} ({len(msgs)} messages)")
    i = next(idx for idx, m in enumerate(msgs) if user_text_of(m).startswith("How does skill system work?"))
    return msgs, tools, user_text_of(msgs[i]), msgs[i + 1]["content"], msgs[i + 1]["reasoning_content"]


# ---------------------------------------------------------------------------
# Step 5 — tzip invocations (teacher ground truth) + skill-tzip file
# ---------------------------------------------------------------------------

def tzip_skill_block():
    body = (TZIP_SKILL_DIR / "SKILL.md").read_text()
    body = re.sub(r"\A---\n.*?\n---\n", "", body).strip("\n")
    return (
        f'<skill name="tzip" location="{TZIP_LOCATION}">\n'
        f"References are relative to {TZIP_SKILL_DIR}.\n\n{body}\n</skill>"
    )


def example_skill_block(base_msgs):
    """The frozen example skill block, taken from the no-argument one-shot in the base conversation."""
    for m in base_msgs:
        if m.get("role") == "user" and user_text_of(m).startswith('<skill name="example"'):
            return user_text_of(m)
    raise RuntimeError("example skill block not found in base conversation")


def generate_sequence_teacher(teacher, base_msgs, tools, example_block):
    """Teacher (thinking off) generates the full interleaved sequence + per-item expectations."""
    seq_msgs = []
    items = []
    for i, (kind, arg, tool_reason, final_reason) in enumerate(SEQ):
        block = tzip_skill_block() if kind == "tzip" else example_block
        text = block + (f"\n\n{arg}" if arg else "")
        user_msg = make_user(text)
        transcript, final = rollout(teacher, base_msgs + seq_msgs + [user_msg], tools, max_turns=4)
        asst_msgs = [dict(m) for m in transcript]
        for m in asst_msgs:  # tool-call turns get the tool reasoning
            if m.get("tool_calls") and tool_reason:
                m["reasoning_content"] = tool_reason
        for m in reversed(asst_msgs):  # last plain reply gets the final reasoning
            if m.get("role") == "assistant" and not m.get("tool_calls"):
                m["reasoning_content"] = final_reason
                break
        seq_msgs += [user_msg] + asst_msgs
        items.append(
            {
                "name": f"{kind} {arg or '(default)'} #{i + 1}",
                "user_text": text,
                "upto": len(seq_msgs),
                "expected": final["content"],
                "needs_tool": kind == "example" and arg != "",
            }
        )
        say(f"  seq[{i + 1:2d}/{len(SEQ)}] {kind} {arg or '(none)':<12} -> {final['content']!r}")
    for it in items:
        it["prefix"] = seq_msgs[: it["upto"]]
        del it["upto"]
    return seq_msgs, items


def write_tzip_file(base_msgs, tools, tzip_msgs, step1, model_cfg):
    step1_user, step1_content, step1_reasoning = step1
    i = next(idx for idx, m in enumerate(base_msgs) if user_text_of(m).startswith("How does skill system work?"))
    msgs = list(base_msgs)
    msgs[i] = make_user(step1_user)
    msgs[i + 1] = {"role": "assistant", "content": step1_content, "reasoning_content": step1_reasoning}
    doc = make_doc(msgs + tzip_msgs, STUDENT_MODEL, model_cfg, tools)
    TZIP_FILE.write_text(json.dumps(doc, ensure_ascii=False, indent=2) + "\n")
    say(f"Wrote {TZIP_FILE.name} ({len(doc['messages'])} messages).")


# ---------------------------------------------------------------------------
# Goal 2 — GEPA optimization of the step-1 pair
# ---------------------------------------------------------------------------

CONSTRAINT = (
    "The step-1 pair must stay a GENERAL rule for any skill block of the form "
    "`<skill> SKILL BODY </skill> [USER MESSAGE]`; it must not mention tzip, example, "
    "or any specific reply text. The student is a 2.6B model: keep the pair short, "
    "concrete, and in first person ('I will ...')."
)

OBJECTIVE = (
    "Maximize the student model's (LiquidAI/LFM2.5-2.6B) accuracy on pi skill invocations. "
    "The student sees a fixed conversation prefix: the pi system prompt, two synthetic Q&A pairs listing "
    "available skills and tools, the step-1 teaching pair (the ONLY text you may improve: step1_user, "
    "step1_assistant, step1_reasoning), and three frozen one-shot demonstrations of the 'example' skill: "
    "invoked with no text -> reply exactly the required line; invoked with 'Hello' -> read the required "
    "reference file, then reply its required word; invoked with 'Hi' -> run the skill script with the "
    "user's text as CLI parameters, then report the output. After the prefix, the user sends skill "
    "invocations: a <skill name=... location=...>SKILL BODY</skill> block, optionally followed by the "
    "user's argument text. The student must treat the block as the active instruction, use the text after "
    "the closing tag as the current argument (never an example embedded in the skill body), follow the "
    "skill's Usage rules for that argument (exact confirmation reply, load reference files, run scripts), "
    "and reply with only the exact confirmation the skill requires. The test invocations are 15 "
    "interleaved messages that switch skills in between: the 'tzip' skill (a token-pruning mode; replies "
    "like 'tzip lite activated' or 'tzip deactivated') with nine mode transitions jumping randomly up and "
    "down the lite/full/ultra ladder and ending in 'tzip off', and the 'example' skill invoked five times: "
    "'Hello' (read the reference file, reply its word), 'call script' (run the script with no parameters), "
    "no extra text (reply the exact line), a fresh argument (run the script with it as parameters), and "
    "'Hello' again after 'tzip off'."
)

BACKGROUND = (
    "The step-1 teaching pair explains the <skill> SKILL BODY </skill> [USER MESSAGE] shape: the block "
    "carries the skill's instructions, the text after the block is the current argument, and the reply is "
    "the exact confirmation the skill requires. Rules for improving it: it must stay GENERAL (no tzip, no "
    "example, no specific reply text), keep teaching the block shape and the argument rule, be written in "
    "the student model's first-person voice, and stay short. The frozen parts (system message, the two "
    "skills/tools Q&A pairs, the three example one-shots) are never optimized. The test interleaves tzip "
    "and example invocations; tzip mode transitions jump both up and down; some example invocations happen "
    "while tzip is still active and one happens after 'tzip off'. Scoring: exact normalized reply match = "
    "1.0, containment = 0.5, otherwise 0.0; example items with an argument also require an actual tool "
    "call, otherwise the score is capped at 0.5."
)


def norm(s):
    s = re.sub(r"\s+", " ", (s or "").strip().lower()).rstrip(".")
    return s


def score_item(example, final_msg, transcript):
    actual = final_msg.get("content") or ""
    e, a = norm(example["expected"]), norm(actual)
    if e and a and e == a:
        score = 1.0
    elif e and a and (e in a or a in e):
        score = 0.5
    else:
        score = 0.0
    tool_calls = [tc for m in transcript if m.get("tool_calls") for tc in m["tool_calls"]]
    if example.get("needs_tool") and not tool_calls:
        score = min(score, 0.5)
    status = "PASS" if score >= 0.999 else ("PARTIAL" if score > 0 else "FAIL")
    side = {
        "Task": example["name"],
        "Status": status,
        "Expected reply": example["expected"],
        "Student reply": actual or "(empty)",
        "Student tool calls": "; ".join(
            f'{tc["function"]["name"]}({tc["function"]["arguments"]})' for tc in tool_calls
        )
        or "none",
        "Student reasoning_content": (final_msg.get("reasoning_content") or "none")[:600],
        "Constraint": CONSTRAINT,
    }
    return score, side


def make_evaluator(student, tools, base_msgs):
    i = next(idx for idx, m in enumerate(base_msgs) if user_text_of(m).startswith("How does skill system work?"))
    before, after = base_msgs[:i], base_msgs[i + 2 :]  # step-1 pair is the only variable part

    def evaluate(candidate, example=None):
        if example is None:
            return 0.0, {"error": "evaluator called without an example"}
        ctx = before + [make_user(candidate["step1_user"])] + [
            {
                "role": "assistant",
                "content": candidate["step1_assistant"],
                "reasoning_content": candidate["step1_reasoning"],
            }
        ] + after + list(example["prefix"]) + [make_user(example["user_text"])]
        try:
            transcript, final = rollout(student, ctx, tools, max_turns=4)
        except Exception as exc:  # noqa: BLE001
            return 0.0, {"Task": example["name"], "Status": "ERROR", "Error": f"{type(exc).__name__}: {exc}", "Constraint": CONSTRAINT}
        return score_item(example, final, transcript)

    return evaluate


def make_reflection_lm(teacher):
    def reflection_lm(prompt):
        msgs = [{"role": "user", "content": prompt}] if isinstance(prompt, str) else prompt
        resp = teacher.forward(messages=msgs)
        return resp.choices[0].message.content or ""

    return reflection_lm


# ---------------------------------------------------------------------------
# main
# ---------------------------------------------------------------------------

def main():
    global API_BASE, API_KEY
    API_BASE, API_KEY, STUDENT_CFG, TEACHER_CFG = load_model_configs()
    say(f"Loaded provider '{PROVIDER}' config for {STUDENT_MODEL} (thinking on) and {TEACHER_MODEL} (thinking off).")
    say(f"API base: {API_BASE[:8]}*** (masked)")

    student, teacher = build_lms(API_BASE, API_KEY, STUDENT_CFG, TEACHER_CFG)

    # sanity check: one cheap student + teacher call
    t_probe = chat(teacher, [{"role": "user", "content": "Reply with the single word: pong"}])
    say(f"Teacher probe: {t_probe['content']!r}")
    s_probe = chat(student, [{"role": "user", "content": "Reply with the single word: pong"}])
    say(f"Student probe: {s_probe['content']!r}")

    # ---- Goal 1 ----
    base_msgs, TOOLS, seed_user, seed_content, seed_reasoning = load_goal1(STUDENT_CFG)

    # ---- Step 5: interleaved tzip/example ground truth (teacher, thinking off) + skill-tzip file ----
    say(f"Step 5: generating {len(SEQ)} interleaved invocations with the teacher model (thinking off)...")
    seq_msgs, items = generate_sequence_teacher(teacher, base_msgs, TOOLS, example_skill_block(base_msgs))
    step1_seed = (seed_user, seed_content, seed_reasoning)
    write_tzip_file(base_msgs, TOOLS, seq_msgs, step1_seed, STUDENT_CFG)

    # ---- Goal 2: GEPA on the step-1 pair ----
    train_items = [items[i] for i in TRAIN_ITEM_IDX]
    dataset = [{**it, "id": f"d-{n + 1}"} for n, it in enumerate(train_items)]
    valset = [{**it, "id": f"v-{n + 1}"} for n, it in enumerate(items)]

    evaluate = make_evaluator(student, TOOLS, base_msgs)
    say(f"Goal 2: GEPA optimization — {len(valset)} validation items, max_metric_calls={MAX_METRIC_CALLS}.")
    result = optimize_anything(
        seed_candidate={
            "step1_user": seed_user,
            "step1_assistant": seed_content,
            "step1_reasoning": seed_reasoning,
        },
        evaluator=evaluate,
        dataset=dataset,
        valset=valset,
        objective=OBJECTIVE,
        background=BACKGROUND,
        config=GEPAConfig(
            engine=EngineConfig(
                run_dir=str(RUN_DIR),
                seed=7,
                max_metric_calls=MAX_METRIC_CALLS,
                parallel=2,
                display_progress_bar=True,
            ),
            reflection=ReflectionConfig(reflection_lm=make_reflection_lm(teacher), reflection_minibatch_size=3),
            stop_callbacks=[
                ScoreThresholdStopper(threshold=0.95),
                NoImprovementStopper(max_iterations_without_improvement=10),
                TimeoutStopCondition(timeout_seconds=5400),
            ],
        ),
    )
    best = result.best_candidate
    best_score = result.val_aggregate_scores[result.best_idx] if result.val_aggregate_scores else float("nan")
    say(f"GEPA done: best val score = {best_score:.3f} over {len(valset)} items.")

    # final per-item validation of the best candidate
    say("\nFinal validation of the optimized step-1 pair:")
    total = 0.0
    for it in items:
        s, side = evaluate(best, it)
        total += s
        say(f"  [{side['Status']:7s}] {it['name']}: {s:.1f} | student: {side.get('Student reply', '')[:80]!r}")
    say(f"  aggregate: {total / len(items):.3f}")

    # write the optimized step-1 pair into the final tzip file + standalone JSON
    write_tzip_file(
        base_msgs, TOOLS, seq_msgs, (best["step1_user"], best["step1_assistant"], best["step1_reasoning"]), STUDENT_CFG
    )
    PAIR_FILE.write_text(json.dumps(best, ensure_ascii=False, indent=2) + "\n")
    say(f"Saved optimized step-1 pair to {PAIR_FILE.name} and into {TZIP_FILE.name}.")
    say("\nOptimized step-1 pair:")
    say(f"  user: {best['step1_user']}")
    say(f"  assistant: {best['step1_assistant']}")
    say(f"  reasoning: {best['step1_reasoning']}")


if __name__ == "__main__":
    main()
