#!/usr/bin/env -S uv run --script
#
# /// script
# requires-python = ">=3.12"
# dependencies = ["dspy", "gepa[full]", "httpx", "orjson", "jinja2"]
# ///

'''
NOTE: this is how you instantiate dspy.LM - keep this string/comment
IMPORTANT: Radon values for API_BASE and API_KEY on demand from `~/.pi/agent/models.json`. Never leak them in text, logs or source code.

```python
lm = dspy.LM(
    f"openai/{model}", # used model
    api_base=API_BASE,
    api_key=API_KEY,
    model_type="chat",
    temperature=..., # read for used model
    max_tokens=16384,
    extra_headers={"x-session-affinity": f"dspy-optim-lfm2.5-2.6b-{session_id}"},  # per model + per REQUEST
    extra_body={
        "top_k": ..., # read for used model, or omit if missing
        "min_p": ..., # read for used model, or omit if missing
        "presence_penalty": ..., # read for used model, or omit if missing
        "repeat_penalty": ..., # read for used model, or omit if missing
    },
)
'''
"""train.py — optimize the slm.ts "skill-system" pair with GEPA.

Pipeline
--------
1. The pi extension `slm.ts` injects a simulated dialogue at the start of
   every session. The LAST pair (user ask + synthetic assistant reply with
   `reasoning_content`) is overridden by the companion extension
   `pair-override.ts` (loaded after slm.ts) from the single file
   `skill-pair.json` next to it. slm.ts itself is never edited.
2. For every evaluation case in `expected-responses/` a fresh
   `pi -p --mode json ...` process is spawned (student model
   LiquidAI/LFM2.5-2.6B, thinking high). The student receives one `<skill>`
   block (+ bare argument) as its user message.
3. Observation channels (both automated here):
   - the JSON event stream (final assistant message, tool calls);
   - the session log `.pi/pi-llm-debugging/<session_id>/NNN-req.json`
     (the latest *-req.json is the most complete context snapshot).
4. Scoring per case:
   - tool-call correctness (name + arguments, e.g. read path / bash script
     path + args);
   - final-reply correctness vs expected-responses (exact line for tzip,
     exact fixed reply / script output report for the example skill);
   - CoT leak: the student's reasoning_content in a later chain message
     must not verbatim-copy (>=8 consecutive words) an earlier assistant
     message's reasoning or answer.
5. GEPA (`gepa.optimize_anything`) evolves the pair
   {"ask", "explain", "thinking"}; the reflection LM is the teacher
   Qwen/Qwen3.8-27B with thinking OFF. The seed `thinking` is generated by
   the teacher in the student's voice per REASONING-LiquidAI-LFM2.5-2.6B.md.
6. All GEPA/dspy intermediate files live under `runs/`; progress is appended
   to `./train.log`.

Usage
-----
    venv/bin/python train.py baseline                 # score current pair
    venv/bin/python train.py optimize                 # run GEPA (resumable)
    venv/bin/python train.py optimize --run-dir runs/gepa-xxx
    venv/bin/python train.py eval --pair path.json    # score an arbitrary pair
"""

import argparse
import hashlib
import json
import os
import re
import select
import shlex
import subprocess
import sys
import threading
import time
from pathlib import Path

import dspy

HERE = Path(__file__).resolve().parent
PAIR_FILE = HERE / "skill-pair.json"
RUNS_DIR = HERE / "runs"
TRAIN_LOG = HERE / "train.log"
REASONING_DOC = HERE / "REASONING-LiquidAI-LFM2.5-2.6B.md"
MODELS_JSON = Path(os.path.expanduser("~/.pi/agent/models.json"))

PROVIDER = "llamacpp"
STUDENT_MODEL = "LiquidAI/LFM2.5-2.6B"
TEACHER_MODEL = "Qwen/Qwen3.8-27B"
PAIR_KEYS = ("ask", "explain", "thinking")

LEAK_WORDS = 8  # consecutive-word overlap threshold for a CoT leak

_log_lock = threading.Lock()
RUN_ID = f"{time.strftime('%m%d-%H%M%S')}-{os.getpid()}"


# --------------------------------------------------------------------------
# logging
# --------------------------------------------------------------------------

def log(msg: str) -> None:
    line = f"[{time.strftime('%Y-%m-%d %H:%M:%S')}] {msg}"
    with _log_lock:
        with open(TRAIN_LOG, "a", encoding="utf-8") as f:
            f.write(line + "\n")
    print(line, flush=True)


# --------------------------------------------------------------------------
# provider config + LMs (API_BASE/API_KEY read from ~/.pi/agent/models.json)
# --------------------------------------------------------------------------

def _models() -> dict:
    raw = MODELS_JSON.read_text()
    try:
        return json.loads(raw)
    except json.JSONDecodeError:
        # pi's models.json may carry trailing commas; strip them and retry
        return json.loads(re.sub(r",(\s*[}\]])", r"\1", raw))


def _sampling(model_id: str) -> dict:
    prov = _models()["providers"][PROVIDER]
    for m in prov.get("models", []):
        if m.get("id") == model_id:
            return m.get("samplingParams", {}) or {}
    return {}


def _endpoints() -> tuple[str, str]:
    prov = _models()["providers"][PROVIDER]
    return prov["baseUrl"], prov["apiKey"]


def teacher_lm() -> dspy.LM:
    """Teacher: Qwen/Qwen3.8-27B, thinking OFF (enable_thinking=false)."""
    api_base, api_key = _endpoints()
    s = _sampling(TEACHER_MODEL)
    extra_body = {
        k: s[k]
        for k in ("top_k", "min_p", "presence_penalty", "repeat_penalty", "top_p")
        if k in s
    }
    extra_body["chat_template_kwargs"] = {
        "enable_thinking": False,
        "preserve_thinking": True,
    }
    return dspy.LM(
        f"openai/{TEACHER_MODEL}",
        api_base=api_base,
        api_key=api_key,
        model_type="chat",
        temperature=s.get("temperature", 1.0),
        max_tokens=16384,
        cache=False,
        num_retries=5,
        extra_headers={"x-session-affinity": f"dspy-optim-lfm2.5-2.6b-{RUN_ID}"},
        extra_body=extra_body,
    )


def make_teacher_complete(lm: dspy.LM):
    """Wrap the teacher LM into a callable returning str (GEPA reflection_lm)."""

    def complete(prompt: str) -> str:
        out = lm(prompt, temperature=0.7)
        if isinstance(out, list):
            return out[0]
        return out

    return complete


def generate_seed_thinking(lm: dspy.LM, ask: str, explain: str) -> str:
    """Teacher (thinking off) writes the synthetic reasoning_content: a
    structured, true chain of thought in the student's voice, following
    REASONING-LiquidAI-LFM2.5-2.6B.md."""
    doc = REASONING_DOC.read_text()
    prompt = f"""{doc}

TASK: You are writing the reasoning_content (the model's private inner
monologue) of one specific assistant message in a pi coding session.

The user message it answers is:
"{ask}"

The assistant's visible reply (already fixed, do not change or repeat it):
"{explain}"

Write ONLY the reasoning_content. Requirements:
- A true chain of thought of 4-8 plain sentences (~400-700 characters), in the
  student model's voice, with the 5-part shape from the guide above:
  1. open by naming the situation in the first person ("The user asks ...");
  2. a short numbered plan (plain "1. ... 2. ..." sentences) for executing ANY
     <skill> block generically: locate the current block, read its name, Usage
     rules and the bare argument after its closing tag, then pick the Usage
     branch matching the argument — a fixed reply to send exactly, a reference
     file to load with the read tool and follow, or a script to run with bash
     passing the argument as CLI parameters and report its output;
  3. an isolation step: if an earlier message contains another skill block or a
     short confirmation line, that task is finished — its words are not this
     argument, and nothing from it may enter this reply or this reasoning;
  4. a self-check / close committing to the exact action the visible reply
     performs: perform the current block's required behavior exactly, never
     explain the skill, never ask, never repeat an earlier confirmation;
  5. a brief paraphrase note: I state the plan in my own words each time and
     never copy these instructions or any earlier message verbatim.
- Skill-agnostic: it must cover simple skills, skills with reference files, and
  skills with scripts, without naming any specific skill.
- Plain prose only: NO markdown (no #, no **, no backticks, no dash bullets),
  no headers. Numbered "1. ..." plan sentences are fine.
- No meta talk (never mention being synthetic or the reasoning itself).
- Anti-echo (IMPORTANT): the user message above already contains a plan
  paragraph. Do NOT reuse any of its sentences or clause order. Express the
  same plan with different, varied wording and a different order where sensible.
- The paraphrase note and the closing marker from the guide (for example
  "Now final output.") must both be present.
- Output the reasoning text only, nothing else."""
    out = lm(prompt, temperature=0.7)
    text = out[0] if isinstance(out, list) else out
    return _clean_field(text)


# --------------------------------------------------------------------------
# pair file (the single file slm.ts reads)
# --------------------------------------------------------------------------

def load_pair(path: Path = PAIR_FILE) -> dict:
    data = json.loads(path.read_text())
    return {k: data[k] for k in PAIR_KEYS if isinstance(data.get(k), str)}


def write_pair(candidate: dict, path: Path = PAIR_FILE) -> None:
    path.write_text(
        json.dumps({k: candidate[k] for k in PAIR_KEYS}, ensure_ascii=False, indent=2) + "\n",
        encoding="utf-8",
    )


_pair_lock = threading.Lock()
_last_pair_hash: str | None = None


def _clean_field(v: str) -> str:
    """Strip reflector artifacts: wrapping code fences and quote marks."""
    s = (v or "").strip()
    if s.startswith("```"):
        s = s.split("\n", 1)[1] if "\n" in s else s[3:]
        if s.rstrip().endswith("```"):
            s = s.rstrip()[:-3]
        s = s.strip()
    if len(s) >= 2 and s[0] == s[-1] and s[0] in "\"'":
        s = s[1:-1].strip()
    return s


def repair_candidate_inplace(candidate: dict) -> None:
    """Fix reflector output where a whole JSON document got stuffed into a
    field: recover each field's value from the embedded JSON, in place (so
    GEPA's population sees the repaired candidate too)."""
    for k in PAIR_KEYS:
        v = candidate.get(k, "")
        s = (v or "").strip()
        if not (s.startswith("{") and len(s) > 300):
            continue
        try:
            doc, _ = json.JSONDecoder().raw_decode(s[s.index("{"):])
        except json.JSONDecodeError:
            continue
        containers = [doc] + [x for x in doc.values() if isinstance(x, dict)]
        for cont in containers:
            cand = cont.get(k)
            if isinstance(cand, str) and len(cand.strip()) >= 30:
                candidate[k] = _clean_field(cand)
                break


def ensure_pair(candidate: dict) -> None:
    """Write skill-pair.json (sanitized) only when the candidate changes."""
    global _last_pair_hash
    clean = {k: _clean_field(candidate.get(k, "")) for k in PAIR_KEYS}
    content = json.dumps(clean, ensure_ascii=False, indent=2)
    h = hashlib.sha256(content.encode("utf-8")).hexdigest()
    with _pair_lock:
        if h == _last_pair_hash:
            return
        PAIR_FILE.write_text(content + "\n", encoding="utf-8")
        _last_pair_hash = h
        log(
            f"pair file updated hash={h[:10]} "
            f"(ask={len(clean['ask'])}c explain={len(clean['explain'])}c thinking={len(clean['thinking'])}c)"
        )


# --------------------------------------------------------------------------
# evaluation cases
# --------------------------------------------------------------------------

_SKILL_BLOCK_RE = re.compile(
    r'^(<skill name="[^"]+" location="([^"]+)">\n[^\n]*\n)(.*)(</skill>)(.*)$',
    re.DOTALL,
)


def refresh_skill_prompt(prompt: str) -> str:
    """Replace the embedded SKILL.md body with the live file at the block's
    location path, so evals track skill updates on disk."""
    m = _SKILL_BLOCK_RE.match(prompt)
    if not m:
        return prompt
    header, loc, tail = m.group(1), m.group(2), m.group(5)
    try:
        live = Path(loc).read_text()
    except OSError:
        return prompt
    return f"{header}\n{live.rstrip()}\n{m.group(4)}{tail}"


def load_cases() -> list[dict]:
    cases = []
    for f in sorted((HERE / "expected-responses").glob("*.json")):
        data = json.loads(f.read_text())
        cases.append(
            {
                "case": data["case"],
                "skill": data.get("skill", ""),
                "argument": data.get("argument", ""),
                "prompt": refresh_skill_prompt(data["user"]["content"][0]["text"]),
                "expected": data["assistant"],
            }
        )
    return cases


# --------------------------------------------------------------------------
# running pi + reading logs
# --------------------------------------------------------------------------

PI_CMD = [
    "pi",
    "-p",
    "--mode", "json",
    "--no-session",
    "--model", f"{PROVIDER}/{STUDENT_MODEL}",
    "--thinking", "high",
    "--no-tools", "--tools", "read,write,edit,bash",
    "--no-skills",
    "--skill", "../../.agents/skills-byterefinery/example/",
    "--skill", "../../.agents/skills-byterefinery/tzip/",
    "--skill", "../../.agents/skills/webfetch",
    "--skill", "../../.agents/skills/websearch",
    "-e", "slm.ts",
    "-e", "pair-override.ts",
]


def run_pi(prompt: str, timeout: int = 90, retries: int = 1) -> dict:
    """Run one single-shot pi eval. Correct answers complete in seconds, so a
    timeout means the student spiralled; retry once before scoring 0 (spirals
    are partly stochastic and re-runs of the same case often succeed)."""
    last_exc: Exception | None = None
    for attempt in range(1 + max(0, retries)):
        try:
            p = subprocess.run(
                PI_CMD + [prompt],
                cwd=str(HERE),
                capture_output=True,
                text=True,
                timeout=timeout,
            )
            break
        except subprocess.TimeoutExpired as e:
            last_exc = e
            if attempt < retries:
                log(f"run_pi timeout (attempt {attempt + 1}), retrying")
                continue
            raise
    events: list[dict] = []
    session_id: str | None = None
    for line in p.stdout.splitlines():
        line = line.strip()
        if not line:
            continue
        try:
            e = json.loads(line)
        except json.JSONDecodeError:
            continue
        events.append(e)
        if session_id is None and e.get("type") == "session":
            session_id = e.get("id")
    return {"rc": p.returncode, "events": events, "session_id": session_id, "stderr": p.stderr}


PI_CMD_RPC = [
    "pi",
    "--mode", "rpc",
    "--no-session",
    "--model", f"{PROVIDER}/{STUDENT_MODEL}",
    "--thinking", "high",
    "--no-tools", "--tools", "read,write,edit,bash",
    "--no-skills",
    "--skill", "../../.agents/skills-byterefinery/example/",
    "--skill", "../../.agents/skills-byterefinery/tzip/",
    "--skill", "../../.agents/skills/webfetch",
    "--skill", "../../.agents/skills/websearch",
    "-e", "slm.ts",
    "-e", "pair-override.ts",
]


def run_pi_chain(prompts: list[str], timeout: int = 300, retries: int = 1) -> dict:
    """Multi-turn session over the RPC protocol (one pi process).

    Sends each prompt as a `prompt` command and waits for the matching
    `agent_end` event before sending the next one. Retries the whole chain
    once on timeout (spirals are partly stochastic).
    """
    last_exc: Exception | None = None
    for attempt in range(1 + max(0, retries)):
        try:
            return _run_pi_chain_once(prompts, timeout)
        except (subprocess.TimeoutExpired, RuntimeError) as e:
            last_exc = e
            if attempt < retries:
                log(f"run_pi_chain failed ({type(e).__name__}, attempt {attempt + 1}), retrying")
                continue
            raise
    raise last_exc  # pragma: no cover


def _run_pi_chain_once(prompts: list[str], timeout: int) -> dict:
    """Single attempt of run_pi_chain."""
    debug_root = HERE / ".pi" / "pi-llm-debugging"
    _debug_before: set[str] = set()
    t_start = time.time()
    try:
        _debug_before = {d.name for d in debug_root.iterdir() if d.is_dir()}
    except FileNotFoundError:
        pass
    proc = subprocess.Popen(
        PI_CMD_RPC,
        cwd=str(HERE),
        stdin=subprocess.PIPE,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        text=True,
        bufsize=1,
    )
    events: list[dict] = []
    turns: list[dict] = []
    t_end = time.time() + timeout

    def new_debug_dirs() -> list[Path]:
        try:
            return [
                d
                for d in debug_root.iterdir()
                if d.is_dir() and d.name not in _debug_before and d.stat().st_mtime >= t_start - 5
            ]
        except FileNotFoundError:
            return []

    def readline() -> str:
        while True:
            if time.time() > t_end:
                raise subprocess.TimeoutExpired(PI_CMD_RPC, timeout)
            r, _, _ = select.select([proc.stdout], [], [], 0.5)
            if r:
                line = proc.stdout.readline()
                if not line:
                    err = (proc.stderr.read() or "")[:300]
                    raise RuntimeError(f"pi rpc closed stdout: {err}")
                line = line.strip()
                if line:
                    return line
            if proc.poll() is not None:
                err = (proc.stderr.read() or "")[:300]
                raise RuntimeError(f"pi rpc exited early: {err}")

    try:
        for i, p in enumerate(prompts):
            cmd = {"id": f"req-{i}", "type": "prompt", "message": p}
            proc.stdin.write(json.dumps(cmd, ensure_ascii=False) + "\n")
            proc.stdin.flush()
            resp = None
            while resp is None:
                e = json.loads(readline())
                events.append(e)
                if e.get("type") == "response" and e.get("id") == f"req-{i}":
                    resp = e
            if not resp.get("success"):
                raise RuntimeError(f"prompt {i} rejected: {resp}")
            while True:
                e = json.loads(readline())
                events.append(e)
                if e.get("type") == "agent_end":
                    turns.append(e)
                    break
    finally:
        try:
            proc.stdin.close()
        except Exception:
            pass
        proc.terminate()
        try:
            proc.wait(timeout=5)
        except Exception:
            proc.kill()
    # RPC emits no session header: find the session via the pi-llm-debugging
    # directory this run created (fallback: a session event, if any).
    session_id = None
    new_dirs = new_debug_dirs()
    if new_dirs:
        session_id = max(new_dirs, key=lambda d: d.stat().st_mtime).name
    for e in events:
        if e.get("type") == "session" and e.get("id"):
            session_id = e.get("id")
            break
    return {"events": events, "session_id": session_id, "turns": turns}


def read_latest_chain(session_id: str) -> list | None:
    """Latest *-req.json of the session: most complete context snapshot."""
    d = HERE / ".pi" / "pi-llm-debugging" / session_id
    if not d.is_dir():
        return None
    reqs = sorted(d.glob("*-req.json"))
    if not reqs:
        return None
    try:
        data = json.loads(reqs[-1].read_text())
        return data.get("messages", [])
    except Exception:
        return None


def events_final_chain(events: list[dict]) -> list | None:
    """Full in-memory message list from the agent_end event (includes the
    final assistant message that no *-req.json contains)."""
    for e in reversed(events):
        if e.get("type") == "agent_end":
            msgs = e.get("messages")
            if msgs:
                return msgs
    return None


def user_text(m: dict) -> str:
    c = m.get("content")
    if isinstance(c, str):
        return c
    if isinstance(c, list):
        return " ".join(b.get("text", "") for b in c if isinstance(b, dict) and b.get("type") == "text")
    return ""


def wire_assistant_from_event(m: dict) -> dict:
    content = m.get("content")
    content = content if isinstance(content, list) else []
    text = next((b.get("text") for b in content if b.get("type") == "text"), None)
    think = next((b.get("thinking") for b in content if b.get("type") == "thinking"), None)
    calls = [
        {"function": {"name": b.get("name"), "arguments": b.get("arguments")}}
        for b in content
        if b.get("type") == "toolCall"
    ]
    return {
        "role": "assistant",
        "content": text,
        "reasoning_content": think or "",
        "tool_calls": calls,
    }


def build_chain(run: dict) -> list | None:
    """Chain = latest request log + the final assistant message (events)."""
    chain = read_latest_chain(run["session_id"]) if run.get("session_id") else None
    ev = events_final_chain(run["events"])
    if not ev:
        return chain
    final = None
    for m in reversed(ev):
        if isinstance(m, dict) and m.get("role") == "assistant":
            final = wire_assistant_from_event(m)
            break
    if final is None:
        return chain
    if chain is None:
        return [final]
    # if the last logged message already equals the final one, do not duplicate
    last = chain[-1] if isinstance(chain[-1], dict) else {}
    if last.get("role") == "assistant" and last.get("reasoning_content") == final.get("reasoning_content") \
            and last.get("content") == final.get("content"):
        return chain
    return chain + [final]


def find_prompt_idx(chain: list, prompt: str) -> int | None:
    idx = None
    for i, m in enumerate(chain):
        if isinstance(m, dict) and m.get("role") == "user" and prompt in user_text(m):
            idx = i
    return idx


def extract_student(chain: list, prompt: str, bound_idx: int | None = None) -> dict:
    """Student-generated messages = assistant messages after the real user
    prompt (the <skill> block), before bound_idx when given."""
    idx = find_prompt_idx(chain, prompt)
    if idx is None:
        return {"students": [], "final_text": None}
    end = bound_idx if bound_idx is not None else len(chain)
    msgs = chain[idx + 1 : end]
    students = []
    for m in msgs:
        if not isinstance(m, dict) or m.get("role") != "assistant":
            continue
        tcs = []
        for tc in m.get("tool_calls") or []:
            fn = tc.get("function", {})
            args = fn.get("arguments")
            if isinstance(args, str):
                try:
                    args = json.loads(args)
                except json.JSONDecodeError:
                    pass
            tcs.append({"name": fn.get("name"), "args": args})
        text = m.get("content")
        students.append(
            {
                "text": text if isinstance(text, str) else None,
                "reasoning": m.get("reasoning_content") or "",
                "tool_calls": tcs,
            }
        )
    final = next((s["text"] for s in reversed(students) if s["text"]), None)
    return {"students": students, "final_text": final}


# --------------------------------------------------------------------------
# scoring
# --------------------------------------------------------------------------

def norm(s: str | None) -> str:
    s = s or ""
    s = re.sub(r"[*_`]", "", s)
    s = re.sub(r"\s+", " ", s).strip().lower()
    return s.strip(".!? ")


def expected_tool(case: dict) -> tuple[str, dict] | None:
    for step in case["expected"]:
        tcs = step.get("tool_calls")
        if tcs:
            fn = tcs[0]["function"]
            args = fn.get("arguments")
            if isinstance(args, str):
                try:
                    args = json.loads(args)
                except json.JSONDecodeError:
                    pass
            return fn.get("name"), args
    return None


def expected_final(case: dict) -> str | None:
    for step in reversed(case["expected"]):
        c = step.get("content")
        if isinstance(c, str) and c.strip():
            return c
    return None


def bash_tokens(command: str) -> tuple[str, list[str]]:
    import posixpath

    toks = shlex.split(command or "")
    # resolve a leading `cd <dir> && ` prefix (the example doc's canonical
    # form: run from the scripts dir as `./example.sh`)
    if len(toks) >= 4 and toks[0] == "cd" and "&&" in toks:
        sep = toks.index("&&")
        cd_dir = toks[1]
        rest = toks[sep + 1:]
        if rest and rest[0] in ("bash", "sh"):
            rest = rest[1:]
        if rest:
            script = rest[0]
            if not script.startswith("/"):
                script = posixpath.normpath(cd_dir.rstrip("/") + "/" + script)
            return script, rest[1:]
    if toks and toks[0] == "bash" and len(toks) > 1:
        return toks[1], toks[2:]
    if toks:
        return toks[0], toks[1:]
    return "", []


def bash_expected_args(case: dict) -> list[list[str]]:
    """Accepted argument token lists for the example script call."""
    c = case["case"]
    if c == "example-by":
        return [["Bye"]]
    if c == "example-hi":
        return [["Hi"]]
    if c == "example-call-script":
        return [[], ["call", "script"]]
    if c == "example-hello-lower":
        return [["hello"]]
    return [[]]


def tool_match(case: dict, students: list[dict]) -> tuple[float, str]:
    exp = expected_tool(case)
    if exp is None:
        called = [tc for s in students for tc in s["tool_calls"]]
        if not called:
            return 1.0, "no tool expected, none made"
        return 0.5, f"no tool expected but called: {called[:2]}"

    exp_name, exp_args = exp
    all_calls = [(s, tc) for s in students for tc in s["tool_calls"]]

    def matches(tc: dict) -> bool:
        if tc.get("name") != exp_name:
            return False
        args = tc.get("args") or {}
        if exp_name == "read":
            return args.get("path") == exp_args.get("path")
        if exp_name == "bash":
            path, tok = bash_tokens(str(args.get("command", "")))
            if case["case"].startswith("webfetch"):
                # script must be webfetch.sh (the skill doc prints an example
                # path from a sibling repo, so accept any scripts/webfetch.sh)
                # with the exact URL/flag tokens from the gold command
                # (trailing slash on the URL is irrelevant)
                def norm_url(ts: list[str]) -> list[str]:
                    return [t[:-1] if t.startswith("http") and t.endswith("/") else t for t in ts]

                exp_path, exp_tok = bash_tokens(
                    str((exp_args or {}).get("command", ""))
                )
                return (
                    path.endswith("scripts/webfetch.sh")
                    and bool(exp_path)
                    and norm_url(tok) == norm_url(exp_tok)
                )
            if not path.endswith("scripts/example.sh"):
                return False
            return tok in bash_expected_args(case)
        return False

    # first student call must match for full credit
    first = all_calls[0][1] if all_calls else None
    if first is not None and matches(first):
        return 1.0, f"first call matches expected ({exp_name})"
    if any(matches(tc) for _, tc in all_calls):
        return 0.5, f"expected {exp_name} call appears but not first: {[tc.get('name') for _, tc in all_calls[:3]]}"
    return 0.0, f"expected {exp_name} {json.dumps(exp_args)[:120]}; got {[(tc.get('name'), str(tc.get('args'))[:80]) for _, tc in all_calls[:3]]}"


def final_match(case: dict, final: str | None) -> tuple[float, str]:
    exp = expected_final(case)
    if exp is None:
        return 0.0, "no expected final text"
    final = final or ""
    n_exp, n_final = norm(exp), norm(final)
    if n_final == n_exp:
        return 1.0, "exact"
    case_name = case["case"]
    if case_name.startswith("tzip-"):
        if n_exp in n_final and len(n_final) <= 2 * len(n_exp):
            return 0.5, f"extra text around expected line: {final[:120]!r}"
        return 0.0, f"expected {exp!r}, got {final[:160]!r}"
    if case_name == "example-empty":
        if n_exp in n_final:
            return 0.5, f"expected exactly {exp!r}, got {final[:160]!r}"
        return 0.0, f"expected {exp!r}, got {final[:160]!r}"
    if case_name == "example-hello":
        first_line = (final or "").strip().splitlines()[0] if final and final.strip() else ""
        if norm(first_line) == n_exp:
            return 0.5, f"expected exactly {exp!r}, got {final[:160]!r}"
        return 0.0, f"expected {exp!r}, got {final[:160]!r}"
    if case_name.startswith("webfetch"):
        if "tangled group" in n_final:
            return 1.0, "fetched page content reported"
        if "tangledgroup.com" in n_final:
            return 0.5, f"URL mentioned but page content missing: {final[:120]!r}"
        return 0.0, f"expected the fetched page content, got {final[:160]!r}"
    # example script cases: the output must be reported
    # (no trailing period in the needle: norm() strips the period from the
    # end of the whole string, so a final ending with the output line would
    # never match a period-terminated needle)
    if "this is example.sh output" in n_final:
        return 1.0, "script output reported"
    if "example.sh output" in n_final:
        return 0.5, f"partial output report: {final[:160]!r}"
    return 0.0, f"expected script output report, got {final[:160]!r}"


def score_case(case: dict, students: list[dict], final: str | None) -> tuple[float, dict]:
    t_score, t_detail = tool_match(case, students)
    f_score, f_detail = final_match(case, final)
    if expected_tool(case) is not None:
        score = 0.5 * t_score + 0.5 * f_score
    else:
        score = f_score
    return score, {"tool": t_detail, "final": f_detail}


# --------------------------------------------------------------------------
# CoT leak detection
# --------------------------------------------------------------------------

PATH_RE = re.compile(r"(?:[A-Za-z0-9_.~*-]+/)+[A-Za-z0-9_.~*-]+")


def strip_paths(s: str) -> str:
    """Remove filesystem paths before leak comparison: quoting the task's
    own location path is data, not a CoT leak."""
    return PATH_RE.sub(" ", s or "")


def words(s: str | None) -> list[str]:
    return re.findall(r"[a-z0-9']+", (s or "").lower())


def longest_common_word_seq(a: str, b: str) -> tuple[int, str]:
    a_w, b_w = words(a), words(b)
    if not a_w or not b_w:
        return 0, ""
    n, m = len(a_w), len(b_w)
    best = 0
    best_end = 0
    prev = [0] * (m + 1)
    for i in range(1, n + 1):
        cur = [0] * (m + 1)
        aw = a_w[i - 1]
        for j in range(1, m + 1):
            if aw == b_w[j - 1]:
                cur[j] = prev[j - 1] + 1
                if cur[j] > best:
                    best = cur[j]
                    best_end = i
        prev = cur
    if best == 0:
        return 0, ""
    return best, " ".join(a_w[best_end - best : best_end])


def cot_leaks(chain: list, prompt: str, bound_idx: int | None = None) -> tuple[list[dict], int, int]:
    """For each student assistant message with reasoning in this turn's window
    (after the prompt, before bound_idx), detect verbatim copying
    (>= LEAK_WORDS consecutive words) from ANY earlier skill message:
    earlier assistant reasoning_content / visible content, or earlier user
    messages containing a <skill> block. The current turn's own skill block
    is the task and is excluded. Tool results are legitimate to quote and are
    excluded as sources.
    Returns (leaks, leaked_msgs, student_msgs_with_reasoning)."""
    idx = find_prompt_idx(chain, prompt)
    if idx is None:
        return [], 0, 0
    end = bound_idx if bound_idx is not None else len(chain)
    cur_skill_m = re.search(r'<skill name="([^"]+)"', prompt)
    cur_skill = cur_skill_m.group(1) if cur_skill_m else None
    leaks: list[dict] = []
    student_msgs = 0
    leaked_msgs = 0
    prev_sources: list[tuple[str, str, int]] = []  # (label, text, position)
    for i, m in enumerate(chain):
        if not isinstance(m, dict):
            continue
        role = m.get("role")
        if role == "assistant":
            rc = m.get("reasoning_content") or ""
            content = m.get("content")
            content = content if isinstance(content, str) else ""
            in_window = idx < i < end
            if in_window and rc:
                student_msgs += 1
                rc_cmp = strip_paths(rc)
                best = None  # (len, snippet, label, position)
                for label, text, pos in prev_sources:
                    L, snippet = longest_common_word_seq(rc_cmp, text)
                    if best is None or L > best[0]:
                        best = (L, snippet, label, pos)
                if best is not None and best[0] >= LEAK_WORDS:
                    # kind: "earlier" = a prior skill message (the injected
                    # pair, an earlier turn's reply/reasoning, or an earlier
                    # user skill block); "self" = the student's own earlier
                    # reasoning in this same turn.
                    leaks.append(
                        {
                            "msg": i,
                            "source": best[2],
                            "kind": "earlier" if best[3] <= idx else "self",
                            "overlap_words": best[0],
                            "overlapped_text": best[1][:300],
                        }
                    )
                    leaked_msgs += 1
            prev_sources.append((f"assistant@{i} reasoning_content", strip_paths(rc), i))
            if content:
                prev_sources.append((f"assistant@{i} content", strip_paths(content), i))
        elif role == "user":
            t = user_text(m)
            if i != idx and "<skill name=" in t:
                src_skill_m = re.search(r'<skill name="([^"]+)"', t)
                src_skill = src_skill_m.group(1) if src_skill_m else None
                # An earlier block of the SAME skill is the same document as
                # the current task — quoting it is legitimate, not a leak.
                # Earlier blocks of OTHER skills remain leak sources.
                if not (cur_skill and src_skill and src_skill == cur_skill):
                    prev_sources.append((f"user@{i} skill block", strip_paths(t), i))
    return leaks, leaked_msgs, student_msgs


# --------------------------------------------------------------------------
# the GEPA evaluator
# --------------------------------------------------------------------------

def is_corrupted(candidate: dict) -> str | None:
    """Detect reflector output that failed to split into plain fields.
    Code fences are tolerated (ensure_pair strips them); a JSON document
    stuffed into a field is not repairable here and is rejected."""
    for k, v in candidate.items():
        if not isinstance(v, str):
            return f"field {k!r} is not a string"
        s = _clean_field(v).strip()
        if s.startswith("{") and ('"thinking"' in s or '"explain"' in s) and len(s) > 300:
            return f"field {k!r} looks like a JSON document, not plain text"
    return None


# Multi-turn scenarios: earlier skill use in the same session, then a new
# skill invocation. They exercise leak PREVENTION: the second turn's reply
# and reasoning must not copy, repeat, or continue the first skill's
# confirmation / rules / arguments.
CHAIN_DEFS = [
    {"chain": "chain-tzip-to-example", "turns": ["tzip-lite", "example-hello"]},
    {"chain": "chain-example-to-tzip", "turns": ["example-hello", "tzip-off"]},
    {"chain": "chain-tzip-full-to-lite", "turns": ["tzip-full", "tzip-lite"]},
]

LEAK_PENALTY = 0.5  # a leaking turn is worth half its accuracy score


def score_turn(case: dict, chain: list, bound_idx: int | None = None) -> tuple[float, dict]:
    """Accuracy for one turn, halved when the turn leaks from earlier skill
    messages (leak PREVENTION is part of the objective)."""
    st = extract_student(chain, case["prompt"], bound_idx)
    base, details = score_case(case, st["students"], st["final_text"])
    leaks, leaked_msgs, student_msgs = cot_leaks(chain, case["prompt"], bound_idx)
    earlier_msgs = {l["msg"] for l in leaks if l["kind"] == "earlier"}
    self_msgs = {l["msg"] for l in leaks if l["kind"] == "self"}
    # The objective penalizes leaking from EARLIER skill messages; the
    # student repeating its own in-turn reasoning is reported separately.
    score = base * (LEAK_PENALTY if earlier_msgs else 1.0)
    return score, {
        "base": base,
        "students": st["students"],
        "tool": details["tool"],
        "final": details["final"],
        "actual_final": st["final_text"] or "",
        "leaked": len(earlier_msgs),
        "self_leaked": len(self_msgs),
        "student_msgs": student_msgs,
        "cot_leak": json.dumps(leaks[:2], ensure_ascii=False)[:500] if leaks else "none",
        "student_reasoning": json.dumps([s["reasoning"][:400] for s in st["students"]], ensure_ascii=False)[:2000],
    }


def score_chain(chain_def: dict, chain: list, by_case: dict) -> tuple[float, list[dict]]:
    """Score a multi-turn scenario: mean of per-turn scores (each leak-penalized)."""
    cases = [by_case[n] for n in chain_def["turns"]]
    idxs = [find_prompt_idx(chain, c["prompt"]) for c in cases]
    per = []
    for k, case in enumerate(cases):
        bound = idxs[k + 1] if k + 1 < len(cases) and idxs[k + 1] is not None else None
        s, d = score_turn(case, chain, bound)
        d["turn"] = case["case"]
        per.append((s, d))
    if not per:
        return 0.0, []
    return sum(s for s, _ in per) / len(per), per


def make_evaluator(cases: list[dict]):
    by_case = {c["case"]: c for c in cases}

    def evaluate(candidate: dict, example: dict):
        name = example["name"]
        repair_candidate_inplace(candidate)
        bad = is_corrupted(candidate)
        if bad is not None:
            log(f"eval {name}: CORRUPTED candidate ({bad})")
            return 0.0, {
                "name": name,
                "error": f"corrupted candidate: {bad}. Every field must be plain prose (no JSON, no code fences, no markdown).",
            }
        ensure_pair(candidate)
        t0 = time.time()
        if example["kind"] == "chain":
            prompts = [by_case[n]["prompt"] for n in example["turns"]]
            try:
                run = run_pi_chain(prompts)
            except (subprocess.TimeoutExpired, RuntimeError) as e:
                log(f"eval {name}: chain failed ({type(e).__name__}: {str(e)[:200]})")
                return 0.0, {"name": name, "error": f"pi chain failed: {str(e)[:200]}"}
            chain = build_chain(run)
            if not chain:
                return 0.0, {"name": name, "error": "no session log / event chain"}
            score, per = score_chain({"turns": example["turns"]}, chain, by_case)
            side = {
                "name": name,
                "score": round(score, 3),
                "turns": [
                    {"turn": d["turn"], "expected_final": expected_final(by_case[d["turn"]]),
                     "actual_final": d["actual_final"][:200], "final_check": d["final"],
                     "cot_leak": d["cot_leak"],
                     "leak_msgs": f"skill={d['leaked']} self={d.get('self_leaked', 0)} of {d['student_msgs']}"}
                    for _, d in per
                ],
                "elapsed_s": round(time.time() - t0, 1),
            }
            for _, d in per:
                log(f"eval {name} [{d['turn']}] base={d['base']:.2f} skill_leak={d['leaked']} self_echo={d.get('self_leaked', 0)}/{d['student_msgs']} final={d['actual_final'][:60]!r}")
            log(f"eval {name:<26} score={score:.2f} t={side['elapsed_s']}s")
            return score, side

        case = by_case[example["case"]]
        try:
            run = run_pi(case["prompt"])
        except subprocess.TimeoutExpired:
            log(f"eval {case['case']}: pi timeout")
            return 0.0, {"name": case["case"], "error": "pi run timed out"}
        chain = build_chain(run)
        if not chain:
            log(f"eval {case['case']}: no chain (rc={run['rc']})")
            return 0.0, {
                "name": case["case"],
                "error": "no session log / event chain",
                "stderr": (run["stderr"] or "")[:500],
            }
        score, d = score_turn(case, chain)
        side = {
            "name": case["case"],
            "score": round(score, 3),
            "expected_tool": str(expected_tool(case)),
            "actual_tools": json.dumps(
                [(tc["name"], str(tc["args"])[:100]) for s in d["students"] for tc in s["tool_calls"]]
            )[:400],
            "tool_check": d["tool"],
            "expected_final": expected_final(case),
            "actual_final": d["actual_final"][:300],
            "final_check": d["final"],
            "cot_leak": d["cot_leak"],
            "cot_leak_msgs": f"skill={d['leaked']} self={d.get('self_leaked', 0)} of {d['student_msgs']}",
            "student_reasoning": d["student_reasoning"],
            "elapsed_s": round(time.time() - t0, 1),
        }
        log(
            f"eval {case['case']:<22} score={score:.2f} (base {d['base']:.2f}) skill_leak={d['leaked']} self_echo={d.get('self_leaked', 0)}/{d['student_msgs']} "
            f"t={side['elapsed_s']}s  final={d['actual_final'][:60]!r}"
        )
        return score, side

    return evaluate


# --------------------------------------------------------------------------
# full-pair evaluation (baseline / final report)
# --------------------------------------------------------------------------

def eval_single(candidate: dict, case: dict) -> tuple[float, dict]:
    t0 = time.time()
    try:
        run = run_pi(case["prompt"])
    except subprocess.TimeoutExpired:
        log(f"eval {case['case']}: pi timeout")
        return 0.0, {"error": "timeout", "actual_final": "", "leaked": 0, "self_leaked": 0, "student_msgs": 0}
    chain = build_chain(run)
    if not chain:
        return 0.0, {"error": "no chain", "actual_final": "", "leaked": 0, "self_leaked": 0, "student_msgs": 0}
    score, d = score_turn(case, chain)
    log(
        f"eval {case['case']:<22} score={score:.2f} (base {d['base']:.2f}) skill_leak={d['leaked']} self_echo={d.get('self_leaked', 0)}/{d['student_msgs']} "
        f"t={time.time()-t0:.0f}s final={d['actual_final'][:60]!r}"
    )
    return score, d


def eval_chain(candidate: dict, chain_def: dict, by_case: dict) -> tuple[float, dict]:
    name = chain_def["chain"]
    prompts = [by_case[n]["prompt"] for n in chain_def["turns"]]
    t0 = time.time()
    try:
        run = run_pi_chain(prompts)
    except (subprocess.TimeoutExpired, RuntimeError) as e:
        log(f"eval {name}: chain failed ({type(e).__name__}: {str(e)[:200]})")
        return 0.0, {"error": str(e)[:200], "actual_final": "", "leaked": 0, "self_leaked": 0, "student_msgs": 0}
    chain = build_chain(run)
    if not chain:
        return 0.0, {"error": "no chain", "actual_final": "", "leaked": 0, "self_leaked": 0, "student_msgs": 0}
    score, per = score_chain(chain_def, chain, by_case)
    leaked = sum(d["leaked"] for _, d in per)
    self_leaked = sum(d.get("self_leaked", 0) for _, d in per)
    n_msgs = sum(d["student_msgs"] for _, d in per)
    log(
        f"eval {name:<26} score={score:.2f} skill_leak={leaked} self_echo={self_leaked}/{n_msgs} t={time.time()-t0:.0f}s "
        + " | ".join(f"[{d['turn']}] {d['actual_final'][:50]!r}" for _, d in per)
    )
    return score, {"actual_final": "", "leaked": leaked, "self_leaked": self_leaked, "student_msgs": n_msgs,
                   "turns": [{"turn": d["turn"], "score": s, **{k: v for k, v in d.items() if k != "turn"}} for s, d in per]}


def evaluate_pair(candidate: dict, cases: list[dict], label: str) -> dict:
    """Full report: all 12 single cases + all 3 multi-turn chains."""
    by_case = {c["case"]: c for c in cases}
    log(f"=== evaluating pair ({label}) on {len(cases)} cases + {len(CHAIN_DEFS)} chains ===")
    ensure_pair(candidate)
    rows = []
    total = 0.0
    n_items = len(cases) + len(CHAIN_DEFS)
    leaked = 0
    self_leaked = 0
    student_msgs = 0
    for case in cases:
        score, details = eval_single(candidate, case)
        total += score
        leaked += details.get("leaked", 0)
        self_leaked += details.get("self_leaked", 0)
        student_msgs += details.get("student_msgs", 0)
        rows.append({"case": case["case"], "score": score, **details})
    for cd in CHAIN_DEFS:
        score, details = eval_chain(candidate, cd, by_case)
        total += score
        leaked += details.get("leaked", 0)
        self_leaked += details.get("self_leaked", 0)
        student_msgs += details.get("student_msgs", 0)
        rows.append({"case": cd["chain"], "score": score, **details})
    acc = 100.0 * total / n_items
    skill_leak_rate = 100.0 * leaked / student_msgs if student_msgs else 0.0
    self_echo_rate = 100.0 * self_leaked / student_msgs if student_msgs else 0.0
    result = {
        "label": label,
        "pair": candidate,
        "accuracy_pct": round(acc, 2),
        "skill_leak_pct": round(skill_leak_rate, 2),
        "skill_leak_detail": f"{leaked}/{student_msgs} student reasoning messages copied an EARLIER skill message",
        "self_echo_pct": round(self_echo_rate, 2),
        "self_echo_detail": f"{self_leaked}/{student_msgs} student reasoning messages repeated the student's own earlier reasoning",
        "cases": rows,
        "timestamp": time.strftime("%Y-%m-%d %H:%M:%S"),
    }
    log(
        f"=== RESULT ({label}) accuracy={acc:.2f}%  skill-message leak={skill_leak_rate:.2f}% "
        f"({leaked}/{student_msgs} msgs)  self-echo={self_echo_rate:.2f}% ({self_leaked}/{student_msgs}) ==="
    )
    for r in rows:
        mark = "OK " if r["score"] >= 1.0 else "PART" if r["score"] > 0 else "FAIL"
        log(f"   {mark} {r['case']:<26} {r['score']:.2f}  skill_leak={r.get('leaked',0)} self_echo={r.get('self_leaked',0)}/{r.get('student_msgs',0)}  final={r.get('actual_final','')[:70]!r}")
    return result


# --------------------------------------------------------------------------
# GEPA optimization
# --------------------------------------------------------------------------

OBJECTIVE = """Make a small student language model (2.6B params) EXECUTE <skill> blocks correctly,
right after seeing the synthetic skill-system pair (the component being optimized:
fields "ask", "explain", "thinking") at the start of the session.

Required behaviors when the next user message contains one <skill> block (optionally
followed by a bare argument after the closing tag):

1. tzip skill — reply with EXACTLY the one-line confirmation and nothing else
   (no bold, no explanation, no extra lines):
   - no argument, "on" or "lite"  ->  tzip lite activated
   - "full"  ->  tzip full activated
   - "ultra" ->  tzip ultra activated
   - "off"   ->  tzip deactivated
2. webfetch skill —
   - bare URL, no other request -> run exactly one bash command: the skill
     dir's scripts/webfetch.sh with the URL (no flags, no cd), using the path
     built from the header's skill directory, then report the fetched content
     from the bash result. Never read the script files, never run webfetch.py.
3. example skill —
   - no extra text      ->  reply exactly: This is an example skill.
   - argument "Hello" (exact case) ->  call the read tool on
     <skill-dir>/references/03-hello.md, then reply exactly: world
   - any other text (including case variants like "hello", or "call script", or
     words like "Hi"/"Bye") ->  call the bash tool running
     <skill-dir>/scripts/example.sh with the text as CLI parameters, then report
     the script output in the reply.
4. The skill dir <skill-dir> is the directory named in the block's `location`
   attribute (the folder containing SKILL.md). Reference files and scripts live
   under it, relative to it.

The student must never explain what a skill is, never ask questions, and never
call read on SKILL.md itself. Argument matching is case-sensitive: only the exact
word "Hello" triggers the reference-file read.

Multi-turn: in later turns the context also contains EARLIER <skill> blocks and
their confirmations (e.g. a short line like a mode confirmation). Those tasks
are finished. The reply to the CURRENT block must not copy, repeat, or continue
an earlier skill's reply or confirmation, must not use an earlier argument, and
the student's reasoning must not import earlier skill messages (skill-message
CoT leak). A turn whose reply or reasoning copies an earlier skill message is
scored at half value. The student re-anchoring on its OWN earlier reasoning
within the same turn (self-echo) is reported separately and is not penalized.
Keep skill-message leak at zero."""

BACKGROUND = """Mechanics:
- The pair is injected by a pi extension as a simulated dialogue at the very start
  of every session: the user message is "ask"; the assistant message is "explain"
  and its reasoning_content is "thinking". This pair sits immediately before the
  real user message (the <skill> block). The student sees "thinking" as the
  assistant's reasoning — it is the strongest behavioral signal for what the
  student does next.
- The student is LiquidAI/LFM2.5-2.6B with thinking ON. It imitates: whatever the
  synthetic reasoning commits to is what the student tends to do.

Student failure modes to fix (observed):
(1) treating the <skill> block as a question and explaining the skill instead of
    executing it;
(2) calling read on SKILL.md before acting;
(3) wrapping the required reply in bold/markdown or adding explanation lines;
(4) CoT leak: copying the previous messages' reasoning or confirmations verbatim
    into its own reasoning — each <skill> block is a fresh, independent
    invocation; nothing may be imported from earlier messages.

Constraints on the component (hard requirements):
- Both "explain" and "thinking" are PLAIN PROSE: no markdown at all (no #,
  no **, no backticks, no dash bullets, no code fences, no tables).
- "explain": directly explains how a skill is USED, skill-agnostic, 3-6 short
  sentences, first person. It must say: a <skill> block is a task to execute
  (never a question to answer); read the block's name, its Usage rules, and the
  bare argument after the current block's closing tag; then do exactly what the
  block's Usage says for that argument — send a required fixed reply exactly,
  or load the named reference file with the read tool and follow it, or run the
  named script with bash passing the argument as CLI parameters and report the
  output; paths come from the block's location attribute; the reply contains
  only what the block requires; and it must state the isolation rule: earlier
  messages may contain other skill blocks or their short confirmations, those
  tasks are finished, ignore them completely, never copy/repeat/continue an
  earlier skill's reply, never use an earlier argument, derive everything from
  the current block only.
- "thinking": a true, structured chain of thought in the student model's voice
  (first person, simple words, no meta talk), 4-8 plain sentences (~400-700
  characters), shaped as: (1) name the situation ("The user asks ...");
  (2) a short numbered plan ("1. ... 2. ...") for executing ANY skill block
  generically (locate block, read Usage + argument after the closing tag, pick
  the matching Usage branch: fixed reply / reference file / script);
  (3) an isolation step: if an earlier message contains another skill block or
  a short confirmation line, that task is finished — its words are not this
  argument, and nothing from it may enter this reply or this reasoning;
  (4) close by committing to the exact action the visible reply performs:
  execute the current block's required behavior, never explain the skill,
  never ask, never repeat an earlier confirmation;
  (5) a brief paraphrase note that the plan is stated in my own words each
  time, never copied verbatim from these instructions or any earlier message.
  It must be skill-agnostic (simple skills, skills with reference files, skills
  with scripts) and must not name any specific skill.
- Do not invent rules that contradict the skills' own Usage sections. Keep all
  three fields; do not change field names.

Evaluator evidence in <side_info>: per-case (and per-turn for multi-turn
chains) score, expected vs actual tool call, expected vs actual final reply,
and leak evidence: skill-message leaks (verbatim overlap of the student's
reasoning with an EARLIER skill message — an earlier assistant message or an
earlier user skill block) are penalized at half value, while self-echo
(overlap with the student's own earlier reasoning in the same turn) is reported
separately. Maximize total score; keep skill-message leak at zero."""


# Small core subset covering the three skill branches (fixed reply via
# "example-empty" is excluded to keep the loop cheap; final validation always
# runs the full set). Core: confirmation line, deactivation, reference-file
# branch, script branch — plus the multi-turn leak chains.
CORE_CASES = ("tzip-lite", "tzip-off", "tzip-full", "example-hello", "example-hi", "webfetch-plain")


def build_examples(cases: list[dict], all_cases: bool) -> list[dict]:
    """GEPA dataset: single cases (core 4 or all 12) + the multi-turn chains."""
    ex = []
    core = cases if all_cases else [c for c in cases if c["case"] in CORE_CASES]
    for c in core:
        ex.append({"kind": "case", "name": c["case"], "case": c["case"], "prompt": c["prompt"]})
    for cd in CHAIN_DEFS:
        ex.append({"kind": "chain", "name": cd["chain"], "turns": cd["turns"]})
    return ex


def run_gepa(args) -> None:
    from gepa.optimize_anything import (
        EngineConfig,
        GEPAConfig,
        MergeConfig,
        ReflectionConfig,
        optimize_anything,
    )

    cases = load_cases()
    examples = build_examples(cases, args.all_cases)
    run_dir = Path(args.run_dir) if args.run_dir else RUNS_DIR / f"gepa-{RUN_ID}"
    run_dir.mkdir(parents=True, exist_ok=True)

    seed = load_pair(Path(args.seed_pair))
    if args.regenerate_thinking:
        log("generating seed 'thinking' with teacher (thinking off)...")
        seed["thinking"] = generate_seed_thinking(teacher_lm(), seed["ask"], seed["explain"])
        log(f"seed thinking: {seed['thinking'][:200]!r}")
    else:
        log(f"seed pair: explain={seed['explain'][:100]!r}... thinking={seed['thinking'][:100]!r}...")

    # baseline before optimizing
    baseline = evaluate_pair(seed, cases, "seed-baseline")
    (run_dir / "seed-baseline.json").write_text(json.dumps(baseline, indent=2))

    teacher = teacher_lm()
    evaluator = make_evaluator(cases)
    log(
        f"starting GEPA: run_dir={run_dir} max_metric_calls={args.max_calls} "
        f"optimization examples={len(examples)} (full eval set={len(cases)} cases + {len(CHAIN_DEFS)} chains) "
        f"reflection_lm={TEACHER_MODEL} (thinking off, callable wrapper)"
    )

    result = optimize_anything(
        seed_candidate=seed,
        evaluator=evaluator,
        dataset=examples,
        objective=OBJECTIVE,
        background=BACKGROUND,
        config=GEPAConfig(
            engine=EngineConfig(
                run_dir=str(run_dir),
                max_metric_calls=args.max_calls,
                parallel=False,
                raise_on_exception=False,
                use_cloudpickle=False,
                track_best_outputs=True,
            ),
            reflection=ReflectionConfig(
                reflection_lm=make_teacher_complete(teacher),
                reflection_minibatch_size=3,
                # one plain-text component per reflection (avoids the
                # reflector emitting the whole JSON dict and corrupting fields)
                module_selector="round_robin",
            ),
            merge=MergeConfig(max_merge_invocations=5),
        ),
    )

    best = result.best_candidate
    best = {k: best.get(k, seed.get(k, "")) for k in PAIR_KEYS}
    log(f"GEPA done. best_idx={result.best_idx} total_metric_calls={result.total_metric_calls}")
    log(f"BEST pair:\nask={best['ask']}\nexplain={best['explain']}\nthinking={best['thinking']}")

    # persist best candidate + activate it as the live pair
    (run_dir / "best-pair.json").write_text(json.dumps(best, ensure_ascii=False, indent=2))
    write_pair(best)
    log("best pair written to skill-pair.json (now live for slm.ts)")

    # final validation of the best candidate
    final = evaluate_pair(best, cases, "best-final")
    (run_dir / "best-final.json").write_text(json.dumps(final, indent=2))

    summary = {
        "run_dir": str(run_dir),
        "best_idx": result.best_idx,
        "total_metric_calls": result.total_metric_calls,
        "best_candidate": best,
        "seed_baseline": {
            "accuracy_pct": baseline["accuracy_pct"],
            "skill_leak_pct": baseline["skill_leak_pct"],
            "self_echo_pct": baseline["self_echo_pct"],
        },
        "best_final": {
            "accuracy_pct": final["accuracy_pct"],
            "skill_leak_pct": final["skill_leak_pct"],
            "self_echo_pct": final["self_echo_pct"],
        },
    }
    (run_dir / "summary.json").write_text(json.dumps(summary, ensure_ascii=False, indent=2))
    log(
        f"SUMMARY: accuracy {baseline['accuracy_pct']}% -> {final['accuracy_pct']}%, "
        f"skill-leak {baseline['skill_leak_pct']}% -> {final['skill_leak_pct']}%, "
        f"self-echo {baseline['self_echo_pct']}% -> {final['self_echo_pct']}%"
    )


# --------------------------------------------------------------------------
# CLI
# --------------------------------------------------------------------------

def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__)
    sub = ap.add_subparsers(dest="cmd", required=True)

    sub.add_parser("baseline", help="score the current skill-pair.json")

    po = sub.add_parser("optimize", help="run GEPA optimization (resumable via --run-dir)")
    po.add_argument("--run-dir", default=None)
    po.add_argument("--max-calls", type=int, default=36)
    po.add_argument(
        "--regenerate-thinking",
        action="store_true",
        help="teacher regenerates the seed 'thinking' field before the run",
    )
    po.add_argument("--seed-pair", default=str(PAIR_FILE),
                    help="pair JSON to start from (default: skill-pair.json)")
    po.add_argument("--all-cases", action="store_true",
                    help="optimize on all 12 cases (default: core 4-case subset)")

    pe = sub.add_parser("eval", help="score an arbitrary pair file")
    pe.add_argument("--pair", default=str(PAIR_FILE))

    args = ap.parse_args()

    log(f"### train.py {args.cmd} started (run_id={RUN_ID}, python={sys.version.split()[0]})")

    if args.cmd == "baseline":
        cases = load_cases()
        pair = load_pair()
        res = evaluate_pair(pair, cases, "baseline")
        out = RUNS_DIR / f"baseline-{RUN_ID}.json"
        out.parent.mkdir(parents=True, exist_ok=True)
        out.write_text(json.dumps(res, indent=2))
        log(f"results saved to {out}")
    elif args.cmd == "optimize":
        run_gepa(args)
    elif args.cmd == "eval":
        cases = load_cases()
        pair = load_pair(Path(args.pair))
        res = evaluate_pair(pair, cases, f"eval:{Path(args.pair).name}")
        out = RUNS_DIR / f"eval-{Path(args.pair).stem}-{RUN_ID}.json"
        out.parent.mkdir(parents=True, exist_ok=True)
        out.write_text(json.dumps(res, indent=2))
        log(f"results saved to {out}")


if __name__ == "__main__":
    main()
